### ISSUE TITLE
Current route not loaded into Route class causing 'resource type not registered' exception

### ISSUE THREAD

**Issue by BrianLangevin** [cloudcreativity/json-api-testing#8]
When using the provided testing methods, the following exception is always thrown:
`CloudCreativity\LaravelJsonApi\Exceptions\RuntimeException: JSON API resource type  is not registered.`

When I changed the parameter function in the `CloudCreativity\LaravelJsonApi\Routing\Route` class to call `\Route::current()` instead of `$this->route`, the issue is resolved.  I believe the Route class is not properly loading in the current route, as the local `$this->route` property is always `null`.

Regular HTTP calls to the api work as expected - the exception is only thrown when running PHPUnit tests.

Here is my example test:

```
class EventsTest extends TestCase
{
	/**
	 * @var string
	 */
	protected $resourceType = 'events';

	/**
	 * A basic test example.
	 *
	 * @return void
	 */
	public function testSearch()
	{
		factory(\App\Models\Event::class, 2)->create();

        	$this->doSearch([
        		'page' => ['number' => 1, 'size' => 10],
        	])->assertSearchedMany();
	}

}
```

And here is the exception stack trace:

```
[2019-08-06 14:39:52] testing.ERROR: JSON API resource type  is not registered. {"exception":"[object] (CloudCreativity\\LaravelJsonApi\\Exceptions\\RuntimeException(code: 0): JSON API resource type  is not registered. at C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Routing\\Route.php:178)
[stacktrace]
#0 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Routing\\Route.php(152): CloudCreativity\\LaravelJsonApi\\Routing\\Route->getTypes()
#1 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Middleware\\Authorize.php(84): CloudCreativity\\LaravelJsonApi\\Routing\\Route->getType()
#2 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), Object(App\\JsonApi\\v2\\DefaultAuthorizer))
#3 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#4 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Middleware\\BootJsonApi.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#5 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\BootJsonApi->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'v2')
#6 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 C:\\Users\\brian\\Code\\acesandaros\\vendor\\barryvdh\\laravel-cors\\src\\HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#15 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#19 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#20 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#21 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#22 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#23 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\
ova\\src\\Http\\Middleware\\ServeNova.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\Users\\brian\\Code\\acesandaros\\app\\Http\\Middleware\\RedirectWWWRequests.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\RedirectWWWRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\Users\\brian\\Code\\acesandaros\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#47 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Testing\\Concerns\\MakesHttpRequests.php(375): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#48 C:\\Users\\brian\\Code\\acesandaros\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Testing\\Concerns\\MakesHttpRequests.php(347): Illuminate\\Foundation\\Testing\\TestCase->call('GET', 'https://acesand...', Array, Array, Array, Array, '[]')
#49 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Testing\\MakesJsonApiRequests.php(103): Illuminate\\Foundation\\Testing\\TestCase->json('GET', 'https://acesand...', Array, Array)
#50 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Testing\\MakesJsonApiRequests.php(118): Tests\\JsonApi\\TestCase->jsonApi('GET', 'https://acesand...', Object(Illuminate\\Support\\Collection), Array, Array)
#51 C:\\Users\\brian\\Code\\acesandaros\\vendor\\cloudcreativity\\laravel-json-api\\src\\Testing\\MakesJsonApiRequests.php(190): Tests\\JsonApi\\TestCase->getJsonApi('https://acesand...', Array, Array)
#52 C:\\Users\\brian\\Code\\acesandaros\\tests\\JsonApi\\Feature\\EventsTest.php(21): Tests\\JsonApi\\TestCase->doSearch()
#53 phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php(1084): Tests\\JsonApi\\Feature\\EventsTest->test_index()
#54 phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php(760): PHPUnit\\Framework\\TestCase->runTest()
#55 phar://C:/bin/phpunit.phar/phpunit/Framework/TestResult.php(565): PHPUnit\\Framework\\TestCase->runBare()
#56 phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php(537): PHPUnit\\Framework\\TestResult->run(Object(Tests\\JsonApi\\Feature\\EventsTest))
#57 phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php(431): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#58 phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php(431): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#59 phar://C:/bin/phpunit.phar/phpunit/TextUI/TestRunner.php(425): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#60 phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php(95): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, true)
#61 phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php(67): PHPUnit\\TextUI\\Command->run(Array, true)
#62 C:\\bin\\phpunit.phar(644): PHPUnit\\TextUI\\Command::main()
#63 {main}
"} 
```

Is there anything I might have missed when setting up the package?

**Comment by lindyhopchris** [comment]
This is definitely a set up problem, as we haven't encountered that and we use the testing extensively. Unfortunately I haven't had time to document the testing yet.

The JSON API route object is bound in the container as a singleton... so if you do anything to cause it to be resolved out of the container before doing the test HTTP request, it won't have the current route on it.

Are you doing anything in the test `setUp()` method before the test is being run? Are you doing anything `boot()` methods of your app's service providers that could potentially cause the route to be resolved out of the container?

**Comment by lindyhopchris** [comment]
Closing due to inactivty.

**Comment by JeffreyDissmann** [comment]
I encounter the same problem.

I cleaned up my setUp() and boot() method to do nothing. Still the same.
Changing of $this->route to \Route::current() works.

Any other hint maybe?
